org: gclindsey
app: building-permits-analysis
service: initialize-permits-database

custom:
  bucket: aws-permits-analysis
  s3_raw_folder: "data/raw/"
  s3_int_folder: "data/interim/"
  s3_processed_folder: "data/processed/"
  filename: "permits"
  db_name: ${ssm:/permits/db_name}
  db_user: ${ssm:/permits/db_user}
  db_password: ${ssm:/permits/db_password~true}
  db_port: 5432

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1
  environment:
    S3_BUCKET: ${self:custom.bucket}
    S3_RAW_FOLDER: ${self:custom.s3_raw_folder}
    S3_INT_FOLDER: ${self:custom.s3_int_folder}
    S3_PROCESSED_FOLDER: ${self:custom.s3_processed_folder}
    FILENAME: ${self:custom.filename}
    DB_NAME: ${ssm:/permits/db_name}
    DB_USER: ${ssm:/permits/db_user}
    DB_PASSWORD: ${ssm:/permits/db_password~true}
    DB_PORT: ${self:custom.db_port}
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - s3:PutObject
  #       - s3:PutObjectAcl
  #       - s3:PutBucketNotification
  #       - s3:GetObject
  #       - s3:ListBucket
  #       - s3:GetObjectAcl
  #     Resource: arn:aws:s3:::${self:custom.bucket}/*

functions:
  initDB:
    handler: init_db.init_db
    events:
      - sns: arn:aws:sns:us-east-1:531868584498:permitsRDSAlertTopic
