AWSTemplateFormatVersion: 2010-09-09
Description: "Deploys a single PostgreSQL RDS instance with EC2 security groups."
Parameters:
  AppName:
    Type: String
    Default: "rds-ec2-sg-test"
  AppVersion:
    Type: String
    Default: 1
  DBInstanceIdentifier:
    Type: String
    Default: "db"
  DBEngine:
    Type: String
    Default: "postgres"
  DBEngineVersion:
    Type: String
    Default: "11.6"
  DBInstanceClass:
    Type: String
    Default: "db.t2.micro"
  DBStorageType:
    Type: String
    Default: "gp2"
  DBAllocatedStorage:
    Type: Number
    Default: 20
  DBName:
    Type: String
    Default: '{{resolve:ssm:/permits/db_name:1}}'
  DBUser:
    Type: String
    Default: '{{resolve:ssm:/permits/db_user:1}}'
  DBPassword:
    Type: String
    Default: '{{resolve:ssm-secure:/permits/db_password:1}}'
    NoEcho: True
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Join 
        - '-'
        - - !Ref AppName
          - !Ref AppVersion
          - !Ref DBInstanceIdentifier
          - !Ref AppVersion
      DBName: !Ref DBName
      AssociatedRoles: 
        - FeatureName: s3Import
          RoleArn: !GetAtt RDSS3ImportRole.Arn
      AllocatedStorage: !Ref DBAllocatedStorage
      DBInstanceClass: !Ref DBInstanceClass
      StorageType: !Ref DBStorageType
      Engine: !Ref DBEngine
      EngineVersion: !Ref DBEngineVersion
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      PubliclyAccessible: true
      Tags:
        - Key: App
          Value: !Ref AppName
        - Key: Version
          Value: !Ref AppVersion
Outputs:
  EndpointDB:
    Description: "Endpoint of the newly created RDS instance"
    Value: !GetAtt RDSInstance.Endpoint.Address
  PortDB:
    Description: "Port of the newly created RDS instance"
    Value: !GetAtt RDSInstance.Endpoint.Port
