AWSTemplateFormatVersion: 2010-09-09
Description: "Deploys a single PostgreSQL RDS instance, SNS Topic and SNS Subscription."
Parameters:
  AppName:
    Type: String
    Default: "building-permits-aws-pipeline"
  DBInstanceIdentifier:
    Type: String
    Default: "permits-rds-instance-postgis-template-1"
  DBEngine:
    Type: String
    Default: "postgres"
  DBEngineVersion:
    Type: String
    Default: "11.6"
  DBInstanceClass:
    Type: String
    Default: "db.t2.micro"
  DBStorageType:
    Type: String
    Default: "gp2"
  DBAllocatedStorage:
    Type: Number
    Default: 20
  DBName:
    Type: String
    Default: '{{resolve:ssm:/permits/db_name:1}}'
  DBUser:
    Type: String
    Default: '{{resolve:ssm:/permits/db_user:1}}'
  DBPassword:
    Type: String
    Default: '{{resolve:ssm-secure:/permits/db_password:1}}'
    NoEcho: True
Resources:
  PermitsDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBName: !Ref DBName
      AllocatedStorage: !Ref DBAllocatedStorage
      DBInstanceClass: !Ref DBInstanceClass
      StorageType: !Ref DBStorageType
      Engine: !Ref DBEngine
      EngineVersion: !Ref DBEngineVersion
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      PubliclyAccessible: true
      Tags:
        - Key: App
          Value: !Ref AppName
Outputs:
  EndpointDB:
    Description: "Endpoint of the newly created Permits RDS instance"
    Value: !GetAtt PermitsDB.Endpoint.Address
  PortDB:
    Description: "Port of the newly created Permits RDS instance"
    Value: !GetAtt PermitsDB.Endpoint.Port
