AWSTemplateFormatVersion: 2010-09-09
Description: "Deploys a single PostgreSQL RDS instance."
Parameters:
  AppName:
    Type: String
    Default: "aws-building-permits-pipeline"
  DBInstanceIdentifier:
    Type: String
    Default: "permits-dev-1"
  DBEngine:
    Type: String
    Default: "postgres"
  DBEngineVersion:
    Type: String
    Default: "11.6"
  DBInstanceClass:
    Type: String
    Default: "db.t2.micro"
  DBStorageType:
    Type: String
    Default: "gp2"
  DBAllocatedStorage:
    Type: Number
    Default: 20
  DBName:
    Type: String
    Default: '{{resolve:ssm:/permits/db_name:1}}'
  DBUser:
    Type: String
    Default: '{{resolve:ssm:/permits/db_user:1}}'
  DBPassword:
    Type: String
    Default: '{{resolve:ssm-secure:/permits/db_password:1}}'
    NoEcho: True
Resources:
  RDSS3ImportRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: 
              Service:
                - rds.amazonaws.com
            Action: sts:AssumeRole
  RDSS3ImportPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: rds-s3-import-policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - Sid: s3import
            Action: 
              - s3:GetObject
              - s3:ListBucket
            Effect: Allow
            Resource: 
              - arn:aws:s3:::aws-permits-analysis
              - arn:aws:s3:::aws-permits-analysis/*
      Roles: 
        - !Ref RDSS3ImportRole
  PermitsDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBName: !Ref DBName
      AllocatedStorage: !Ref DBAllocatedStorage
      DBInstanceClass: !Ref DBInstanceClass
      StorageType: !Ref DBStorageType
      Engine: !Ref DBEngine
      EngineVersion: !Ref DBEngineVersion
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      PubliclyAccessible: true
      Tags:
        - Key: App
          Value: !Ref AppName
Outputs:
  EndpointDB:
    Description: "Endpoint of the newly created Permits RDS instance"
    Value: !GetAtt PermitsDB.Endpoint.Address
  PortDB:
    Description: "Port of the newly created Permits RDS instance"
    Value: !GetAtt PermitsDB.Endpoint.Port
