AWSTemplateFormatVersion: 2010-09-09
Description: "Deploys a single PostgreSQL RDS instance and S3 bucket."
Parameters:
  AppName:
    Type: String
    Default: "aws-permits-pipeline"
  AppVersion:
    Type: String
    Default: 1
  DBInstanceIdentifier:
    Type: String
    Default: "db"
  DBEngine:
    Type: String
    Default: "postgres"
  DBEngineVersion:
    Type: String
    Default: "11.6"
  DBInstanceClass:
    Type: String
    Default: "db.t2.micro"
  DBStorageType:
    Type: String
    Default: "gp2"
  DBAllocatedStorage:
    Type: Number
    Default: 20
  DBName:
    Type: String
    Default: '{{resolve:ssm:/permits/db_name:1}}'
  DBUser:
    Type: String
    Default: '{{resolve:ssm:/permits/db_user:1}}'
  DBPassword:
    Type: String
    Default: '{{resolve:ssm-secure:/permits/db_password:1}}'
    NoEcho: True
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
Resources:
  RDSS3ImportPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Join
        - '-'
        - - !Ref Stage
          - !Ref AppName
          - !Ref AppVersion
          - rds-s3-import-policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - Sid: s3import
            Action: 
              - s3:GetObject
              - s3:ListBucket
            Effect: Allow
            Resource: 
              - !Join 
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref DataBucket
              - !Join 
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref DataBucket
                  - '/*'
      Roles: 
        - !Ref RDSS3ImportRole
  RDSS3ImportRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - '-'
        - - !Ref Stage
          - !Ref AppName
          - !Ref AppVersion
          - rds-s3-import-role
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: 
              Service:
                - rds.amazonaws.com
            Action: sts:AssumeRole
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Join 
        - '-'
        - - !Ref Stage
          - !Ref AppName
          - !Ref AppVersion
          - !Ref DBInstanceIdentifier
      DBName: !Ref DBName
      AssociatedRoles: 
        - FeatureName: s3Import
          RoleArn: !GetAtt RDSS3ImportRole.Arn
      AllocatedStorage: !Ref DBAllocatedStorage
      DBInstanceClass: !Ref DBInstanceClass
      StorageType: !Ref DBStorageType
      Engine: !Ref DBEngine
      EngineVersion: !Ref DBEngineVersion
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      PubliclyAccessible: true
      Tags:
        - Key: App
          Value: !Ref AppName
        - Key: Version
          Value: !Ref AppVersion
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join 
        - '-'
        - - !Ref Stage
          - !Ref AppName
          - !Ref AppVersion
          - 'data'
          - !Ref AWS::Region
          - !Ref AWS::AccountId
Outputs:
  EndpointDB:
    Description: "Endpoint of the newly created RDS instance"
    Value: !GetAtt RDSInstance.Endpoint.Address
  PortDB:
    Description: "Port of the newly created RDS instance"
    Value: !GetAtt RDSInstance.Endpoint.Port
  DataBucket:
    Description: "S3 Bucket for storing data."
    Value: !Ref DataBucket
