AWSTemplateFormatVersion: 2010-09-09
Description: "Deploys a single RDS instance."
Parameters:
  DBInstanceIdentifier:
    Type: String
    Default: "permits-instance"
  DBEngine:
    Type: String
    Default: "postgres"
  DBEngineVersion:
    Type: String
    Default: "11.4"
  DBInstanceClass:
    Type: String
    Default: "db.t3.small"
  DBStorageType:
    Type: String
    Default: "gp2"
  DBAllocatedStorage:
    Type: Number
    Default: 20
  DBName:
    Type: String
    Default: "permits-db"
  DBUser:
    Type: String
    Default: "masteruser"
  DBPassword:
    Type: String
    Default: "5up3r53cr3tPa55w0rd"
    NoEcho: True
Resources:
  PermitsDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier:
        Ref: DBInstanceIdentifier
      DBName:
        Ref: DBName
      AllocatedStorage:
        Ref: DBAllocatedStorage
      DBInstanceClass:
        Ref: DBInstanceClass
      StorageType:
        Ref: DBStorageType
      Engine:
        Ref: DBEngine
      EngineVersion:
        Ref: DBEngineVersion
      MasterUsername:
        Ref: DBUser
      MasterUserPassword:
        Ref: DBPassword
      Tags:
        - Key: App
          Value: "building-permits-aws-pipeline"
Outputs:
  EndpointDB:
    Description: "Endpoint of the newly created RDS master"
    Value: !GetAtt PermitsDB.Endpoint.Address
  PortDB:
    Description: "Port of the newly created RDS master and replica"
    Value: !GetAtt PermitsDB.Endpoint.Port