org: gclindsey
app: building-permits-analysis
service: building-permits-analysis

package:
  exclude:
    - src/functions/ingest/events/*

custom:
  bucket: aws-permits-analysis

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1
  environment:
    S3_BUCKET: ${self:custom.bucket}
    S3_RAW_FOLDER: "raw/"
    S3_PROCESSED_FOLDER: "processed/"
    PERMITS_URL: "https://data.lacity.org/api/views/yv23-pmwf/rows.csv"
    DB_NAME: ${ssm:/permits/db_name}
    DB_USER: ${ssm:/permits/db_user}
    DB_PASSWORD: ${ssm:/permits/db_password~true}
    DB_PORT: 5432
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
        - s3:PutBucketNotification
        - s3:GetObject
        - s3:ListBucket
        - s3:GetObjectAcl
      Resource: arn:aws:s3:::${self:custom.bucket}/*

functions:
  fetchRawData:
    handler: ingest/fetch_raw_data.fetch_raw_data
    layers: 
      - arn:aws:lambda:us-east-1:531868584498:layer:fetchDataLibs:1
    timeout: 300
  transformRawData:
    handler: ingest/transform_raw_data.transform_raw_data
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: raw/
            - suffix: .csv
          existing: true
    layers:
      - arn:aws:lambda:us-east-1:531868584498:layer:pandasLibs:1
