org: gclindsey
app: building-permits-analysis
service: serverless-permits-rds-pipeline

custom:
  bucket: aws-permits-analysis
  s3_raw_folder: "data/raw/"
  s3_int_folder: "data/interim/"
  s3_processed_folder: "data/processed/"
  permits_url: "https://data.lacity.org/api/views/yv23-pmwf/rows.csv"
  #permits_url: "https://query.data.world/s/3jh2lg45et7dhrpolk4in4ye24mnaj"
  filename: "permits"
  db_name: ${ssm:/permits/db_name}
  db_user: ${ssm:/permits/db_user}
  db_password: ${ssm:/permits/db_password~true}
  db_port: 5432
  
provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1
  environment:
    S3_BUCKET: ${self:custom.bucket}
    S3_RAW_FOLDER: ${self:custom.s3_raw_folder}
    S3_INT_FOLDER: ${self:custom.s3_int_folder}
    S3_PROCESSED_FOLDER: ${self:custom.s3_processed_folder}
    PERMITS_URL: ${self:custom.permits_url}
    FILENAME: ${self:custom.filename}
    DB_NAME: ${ssm:/permits/db_name}
    DB_USER: ${ssm:/permits/db_user}
    DB_PASSWORD: ${ssm:/permits/db_password~true}
    DB_PORT: ${self:custom.db_port}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
        - s3:PutBucketNotification
      Resource: arn:aws:s3:::${self:custom.bucket}/*

functions:
  fetchData: # fetch the data from internet
    handler: fetch_data.fetch_data
    layers: 
      - arn:aws:lambda:us-east-1:531868584498:layer:requestsLayer-p36-p37-p38:1
    timeout: 200
    memorySize: 1536
    # events:
    #   - sns: arn:aws:sns:us-east-1:531868584498:permitsRDSAlertTopic
  initDatabase: # initialize the database from snapshot
    handler: init_db.init_db
    layers: 
      - arn:aws:lambda:us-east-1:898466741470:layer:psycopg2-py37:3
  loadDatabase:
    handler: load_db.load_db
    layers:
      - arn:aws:lambda:us-east-1:898466741470:layer:psycopg2-py37:3

