org: gclindsey
app: building-permits-analysis
service: building-permits-analysis

custom:
  bucket: aws-permits-analysis

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1
  environment:
    S3_BUCKET: ${self:custom.bucket}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

package:
  exclude:
    - .venv/*

functions:
  fetchData:
    handler: raw_fetch.raw_fetch
    environment:
      S3_KEY: "raw/"
    layers: 
      - arn:aws:lambda:us-east-1:531868584498:layer:fetchDataLibs:1
    timeout: 300
  loadData:
    handler: raw_transform.raw_transform
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: raw/
            - suffix: .csv
    environment:
      S3_KEY: "raw/"
    layers:
      - pandas layer
